In [1]:
!python3 '/kaggle/input/vrp-rl5/project2_2/main.py'

Detected device cuda
Starting VRP training
Train data: <Tasks.vrp.VehicleRoutingDataset object at 0x7d15d47c3850>
Actor: DRL4VRP(
  (static_embedding): Embedding(
    (conv): Conv1d(2, 128, kernel_size=(1,), stride=(1,))
  )
  (dynamic_embedding): Embedding(
    (conv): Conv1d(2, 128, kernel_size=(1,), stride=(1,))
  )
  (decoder): Embedding(
    (conv): Conv1d(2, 128, kernel_size=(1,), stride=(1,))
  )
  (pointer): Pointer(
    (gru): GRU(128, 128, batch_first=True)
    (embedding_attn): Attention()
    (drop_rnn): Dropout(p=0.1, inplace=False)
    (drop_hh): Dropout(p=0.1, inplace=False)
  )
) 
Critic: StateCritic(
  (static_embedding): Embedding(
    (conv): Conv1d(2, 128, kernel_size=(1,), stride=(1,))
  )
  (dynamic_embedding): Embedding(
    (conv): Conv1d(2, 128, kernel_size=(1,), stride=(1,))
  )
  (fc1): Conv1d(256, 20, kernel_size=(1,), stride=(1,))
  (fc2): Conv1d(20, 20, kernel_size=(1,), stride=(1,))
  (fc3): Conv1d(20, 1, kernel_size=(1,), stride=(1,))
)
Starting training

In [2]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Detected device {}'.format(device))

Detected device cuda


In [4]:
import os
os.chdir('/kaggle/input/vrp-rl5/project2_2')
from main import test_vrp
from Models.actor import DRL4VRP
from Tasks.vrp import VehicleRoutingDataset

actor_checkpoint = '/kaggle/working/vrp/10/20_38_59.265263/actor.pt'

dataset = VehicleRoutingDataset(1000000, 10)

#Establish some features of dataset 
dataset.static_size = 2
dataset.dynamic_size = 2

# Define and load model actor
actor = DRL4VRP(dataset.static_size, dataset.dynamic_size, 128, 
                    dataset.update_dynamic, dataset.update_mask, num_layers=1, dropout=0.1).to(device)
actor.load_state_dict(torch.load(actor_checkpoint, map_location=device))



Detected device cuda


<All keys matched successfully>

In [18]:
test_vrp('/kaggle/input/vrp-rl5/project2_2/input.txt',actor)

Starting VRP testing
tensor([[[0.5508],
         [0.3597]]], device='cuda:0')
tensor([[[0.5508, 0.4419, 0.3837, 0.4841, 0.5721, 0.9528, 0.0000, 1.0000,
          0.6946, 0.0183, 0.3741],
         [0.3597, 0.8190, 1.0000, 0.0245, 0.3496, 0.3837, 0.2337, 0.2345,
          0.0000, 0.4989, 0.3444]]], device='cuda:0')
tensor([[[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000, 1.0000],
         [0.0000, 0.2160, 0.3560, 0.3600, 0.4240, 0.2960, 0.2520, 0.2920,
          0.0440, 0.3600, 0.2440]]], device='cuda:0')
Computed tour indices: [[6, 9, 1, 8, 0, 10, 2, 5, 0, 3, 7, 0, 4, 0]]
tensor([[ 6,  9,  1,  8,  0, 10,  2,  5,  0,  3,  7,  0,  4,  0]],
       device='cuda:0')


/kaggle/input/vrp-rl5/project2_2/Tasks/vrp.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(tensor.data, device=dynamic.device)


Total distance traveled: 6.093073820515615
